<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <TargetFrameworks Condition=" '$(OS)' == 'Windows_NT' ">$(TargetFrameworks);net462;net472</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies> <!-- https://github.com/Tyrrrz/GitHubActionsTestLogger/issues/5 -->
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AngleSharp.Js\AngleSharp.Js.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Fixtures\Html5Test\**\*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp.Css" />
    <PackageReference Include="AngleSharp.Io" />
    <PackageReference Include="AngleSharp.Xml" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="GitHubActionsTestLogger">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
